apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: guestbook-app # CRITICAL: Keeps it isolated
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 2 # High Availability
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          env:
            # INJECTION: This pulls the "redis-service" value from the ConfigMap
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
